# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.10.0 9c0d3d3"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "p256-test"
template_type = "Rust"

[[contracts]]
name = "k256-test"
template_type = "Rust"

[[contracts]]
name = "rsa-test"
template_type = "Rust"

[[contracts]]
name = "ed25519-test"
template_type = "Rust"

[[contracts]]
name = "schnorr-test"
template_type = "Rust"
