[workspace]

[package]
name = "ml-dsa-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = { version = "1.0.0", default-features = false, features = ["allocator", "dummy-atomic"] }
# ml-dsa = { git = "https://github.com/RustCrypto/signatures", default-features = false, rev = "66473ec" }
ml-dsa = { git = "https://github.com/XuJiandong/signatures.git", default-features = false, rev = "591a7bb" }
hex = { version = "0.4", default-features = false, features = ["alloc"] }

[profile.release]
overflow-checks = true
opt-level = 3
panic = 'abort'
strip = true
codegen-units = 1

[profile.dev]
strip = true
opt-level = 1
debug = false
panic = 'abort'
debug-assertions = true
